#!/usr/bin/env bash

# script/build: Build container images locally for testing

IMG="localhost/mkdocs-material:6.1.0"

# Avoid overwritting existing image tag
errorMsg="ERROR: ${IMG} already exists. Please, update the tag version"
[[ $(buildah images -q "$IMG" &>/dev/null) ]] && echo "$errorMsg" && exit 1

buildah bud -t "$IMG" -f Dockerfile .
